name: Generate steamdb2 Directory Update Times

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-dir-times:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate last-modified times for steamdb2/ first-level directories
        run: |
          set -eo pipefail
          mkdir -p output
          echo "[" > output/steamdb2_dir_times.json
          first=true
          for dir in steamdb2/*; do
            if [ -d "$dir" ]; then
              # 取得目錄內所有檔案的最後修改時間（最晚的那一個）
              files=$(find "$dir" -type f)
              if [ -z "$files" ]; then
                continue
              fi
              timestamp=$(git log -1 --format="%cI" -- $files)

              # 判斷是否為新目錄（所有檔案的最早 commit 都相同）
              first_commit=$(git log --diff-filter=A --format="%H" -- "$dir" | head -n 1)
              last_commit=$(git log -1 --format="%H" -- $files)
              if [ "$first_commit" = "$last_commit" ]; then
                change_type="added"
              else
                change_type="modified"
              fi

              dir_name=$(basename "$dir")

              # 輸出 JSON 條目
              if [ "$first" = true ]; then
                first=false
              else
                echo "," >> output/steamdb2_dir_times.json
              fi
              echo "{\"directory\": \"${dir_name}\", \"last_modified\": \"${timestamp}\", \"change_type\": \"${change_type}\"}" >> output/steamdb2_dir_times.json
            fi
          done
          echo "]" >> output/steamdb2_dir_times.json

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/steamdb2_dir_times.json
          git diff --cached --quiet || git commit -m "Update steamdb2_dir_times.json"
          git push
