name: Generate steamdb2 Directory Update Times

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-dir-times:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate last-modified times for steamdb2/ first-level directories
        run: |
          set -eo pipefail
          mkdir -p output
          echo "[" > output/steamdb2_dir_times.json
          first=true

          for dir in steamdb2/*; do
            if [ -d "$dir" ]; then
              dir_name=$(basename "$dir")

              # 收集該目錄下所有檔案最後變動的時間，找出最晚的那個
              latest_ts=""
              for file in $(find "$dir" -type f); do
                ts=$(git log -1 --format="%ct" -- "$file" || echo "")
                if [ -n "$ts" ] && { [ -z "$latest_ts" ] || [ "$ts" -gt "$latest_ts" ]; }; then
                  latest_ts=$ts
                fi
              done

              # 轉為 ISO 格式（如有）
              if [ -n "$latest_ts" ]; then
                iso_ts=$(date -u -d "@$latest_ts" +%Y-%m-%dT%H:%M:%SZ)
              else
                iso_ts="null"
              fi

              # 判斷是否為新增
              added_commit=$(git log --diff-filter=A --format="%H" -- "$dir" | head -n 1)
              change_type="modified"
              if [ -n "$added_commit" ]; then
                change_type="added"
              fi

              # 輸出 JSON 條目
              if [ "$first" = true ]; then
                first=false
              else
                echo "," >> output/steamdb2_dir_times.json
              fi

              echo "{\"directory\": \"${dir_name}\", \"last_modified\": \"${iso_ts}\", \"change_type\": \"${change_type}\"}" >> output/steamdb2_dir_times.json
            fi
          done

          echo "]" >> output/steamdb2_dir_times.json

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/steamdb2_dir_times.json
          git diff --cached --quiet || git commit -m "Update steamdb2_dir_times.json"
          git push
