name: Generate steamdb2 Directory Update Times

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-dir-times:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate last-modified times for steamdb2/ first-level directories
        run: |
          set -eo pipefail
          mkdir -p output
          echo "[" > output/steamdb2_dir_times.json
          first=true
          
          for dir in steamdb2/*; do
            if [ -d "$dir" ]; then
              dir_name=$(basename "$dir")
          
              # 找出這個子目錄中所有被 git 管理的檔案
              tracked_files=$(git ls-files "$dir")
          
              if [ -z "$tracked_files" ]; then
                # 該目錄下沒有任何被 git 跟蹤的檔案，跳過
                continue
              fi
          
              # 找出這些檔案中最後一次 commit 的時間（最新的）
              latest_commit_time=$(git log -1 --format="%ct" -- $tracked_files)
          
              # 轉為 ISO 8601 格式
              iso_ts=$(date -u -d "@$latest_commit_time" +%Y-%m-%dT%H:%M:%SZ)
          
              # 判斷是否為新目錄（所有檔案的首次 commit 是否等於最後一次 commit）
              first_commit=$(git log --diff-filter=A --format="%H" -- $tracked_files | sort | head -n 1)
              last_commit=$(git log -1 --format="%H" -- $tracked_files)
              if [ "$first_commit" = "$last_commit" ]; then
                change_type="added"
              else
                change_type="modified"
              fi
          
              # 寫入 JSON 條目
              if [ "$first" = true ]; then
                first=false
              else
                echo "," >> output/steamdb2_dir_times.json
              fi
          
              echo "{\"directory\": \"${dir_name}\", \"last_modified\": \"${iso_ts}\", \"change_type\": \"${change_type}\"}" >> output/steamdb2_dir_times.json
            fi
          done
          
          echo "]" >> output/steamdb2_dir_times.json


      - name: Commit and push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/steamdb2_dir_times.json
          git diff --cached --quiet || git commit -m "Update steamdb2_dir_times.json"
          git push
