name: Generate steamdb2 Directory Update Times

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-dir-times:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # <== 這行非常關鍵，允許你用 git log 查全部歷史

      - name: Generate last-modified times for steamdb2/ first-level directories
        run: |
          mkdir -p output
          echo "[" > output/steamdb2_dir_times.json
          first=true

          for dir in steamdb2/*; do
            if [ -d "$dir" ]; then
              dir_name=$(basename "$dir")

              # 找出此目錄下的所有 git 管理的檔案
              files=$(git ls-files "$dir")
              if [ -z "$files" ]; then
                continue
              fi

              # 對所有檔案執行 git log 取最大時間
              latest_ts=0
              for f in $files; do
                ts=$(git log -1 --format="%ct" -- "$f")
                if [ "$ts" -gt "$latest_ts" ]; then
                  latest_ts=$ts
                fi
              done

              iso_ts=$(date -u -d "@$latest_ts" +%Y-%m-%dT%H:%M:%SZ)

              # 是否為 added？
              first_commit=$(git log --diff-filter=A --format="%H" -- $files | sort | head -n 1)
              last_commit=$(git log -1 --format="%H" -- $files)
              if [ "$first_commit" = "$last_commit" ]; then
                change_type="added"
              else
                change_type="modified"
              fi

              if [ "$first" = true ]; then
                first=false
              else
                echo "," >> output/steamdb2_dir_times.json
              fi

              echo "{\"directory\": \"${dir_name}\", \"last_modified\": \"${iso_ts}\", \"change_type\": \"${change_type}\"}" >> output/steamdb2_dir_times.json
            fi
          done

          echo "]" >> output/steamdb2_dir_times.json

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/steamdb2_dir_times.json
          git diff --cached --quiet || git commit -m "Update steamdb2_dir_times.json"
          git push
