name: Generate steamdb2 File Update Times

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-file-times:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate last-modified times for steamdb2/ first-level subdirectories
        run: |
          set -eo pipefail
          mkdir -p output
          echo "[" > output/steamdb2_file_times.json
          first=true
          for dir in steamdb2/*; do
            if [ -d "$dir" ]; then
              find "$dir" -maxdepth 1 -type f | while read file; do
                timestamp=$(git log -1 --format="%cI" -- "$file")
                if [ "$first" = true ]; then
                  first=false
                else
                  echo "," >> output/steamdb2_file_times.json
                fi
                echo "{\"file\": \"${file}\", \"last_modified\": \"$timestamp\"}" >> output/steamdb2_file_times.json
              done
            fi
          done
          echo "]" >> output/steamdb2_file_times.json

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/steamdb2_file_times.json
          git diff --cached --quiet || git commit -m "Update steamdb2_file_times.json"
          git push
